language: c++

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x32 -extension GLX"
  - "export AUDIODEV=null"
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update

install:
  - sudo apt-get install haxe -y --force-yes
  - sudo apt-get install g++-multilib gcc-multilib
  - sudo apt-get install mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev -y
  - sudo apt-get install libgc-dev
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib install hxcpp
  - haxelib install format
  - haxelib dev lime $(pwd)

script:
  - haxelib run lime rebuild linux -64 -Dlegacy
  - haxelib run lime rebuild linux -64
  - haxelib run lime rebuild tools

notifications:
  slack: openfl:sBwVO0kgB7EuWLYzZzUezVIz
